### ISSUE TITLE
Can't build with prebuilt libril

### ISSUE THREAD

**Issue by TeomanM** [SonyMTKDev/android_device_sony_mt6757-common#1]
Can't be built with the last commit that adds prebuilt libril. Setting env variable `ALLOW_MISSING_DEPENDENCIES=true` leads to ninja make error. I'm trying to build with lineageos 15.1 source.
Removing `BOARD_PROVIDES_LIBRIL := true` from BoardConfigCommon.mk allows the build to continue but i guess this would lead to modem/radio issues. Is this caused by lineage's libraries?

Build log:

`hardware/ril/reference-ril/Android.mk: error: "libreference-ril (SHARED_LIBRARIES android-arm64) missing libril (SHARED_LIBRARIES android-arm64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/ril/reference-ril/Android.mk: error: "libreference-ril (SHARED_LIBRARIES android-arm) missing libril (SHARED_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/ril/rild/Android.mk: error: "rild (EXECUTABLES android-arm64) missing libril (SHARED_LIBRARIES android-arm64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:844: error: exiting from previous errors.
18:29:08 lineage_redwood failed with: exit status 1`

**Comment by danielkot** [comment]
Are you able to boot redwood (sony xperia xa1 ultra dual)?

**Comment by TeomanM** [comment]
Haven't tried it yet. I'm trying to build for the single SIM model (g3221). I think setting `BOARD_PROVIDES_LIBRIL := true` points to a ril library that doesn't exist in this device tree. But hey, it's nice to see I'm not the only one trying to build this :smiling_face_with_tear:

**Comment by danielkot** [comment]
On redwood (g3212) it doesn't boot even lineageos logo... but in twrp in `/data/dalvik-cache` there are files. Well it something works.

**Comment by TeomanM** [comment]
If you're using Sony's stock, that version has force-encrypt and dm-verity(a.k.a AVB) and if you try to change the core partitions it will give you a bootloop. And yes, there will be no boot animation. I learned this when I was trying to get root. 
If you haven't tried this, flash stock first and don't boot into the system (it will activate force-encrypt and dm-verity at first boot) then flash TWRP and from there you can try to flash lineage. This is how I got magisk to work and get root with this device. Booting into the system before flashing lineage in any of these steps will give you a bootloop.

**Comment by TeomanM** [comment]
Alternatively, you can try formatting data (user data) with TWRP and flashing [THIS](https://zackptg5.com/android.php#disverfe) and then try to flash lineage. Sorry for the multiple replies, forgot to add this.

**Comment by danielkot** [comment]
I have formatted `/data` and `/system` before flashing los15.1. Also I have tried that zip disabler many times, none works.

**Comment by danielkot** [comment]
On xda [forum](https://forum.xda-developers.com/f/sony-xperia-xa1-roms-kernels-recoveries-other.6248) there are half(?)-gsi that is twrp backup of system BUT FOR STANDARD XA1.

**Comment by TeomanM** [comment]
Just flashed it, it boots but has some problems. First of all SIM doesn't work (from my very uneducated guess) this may be because of the missing ril blob that stock rom seems to have. Audio and camera also doesn't work. And partitioning is a mess. It creates a lot of partitions (about 20) that are unused. This may be because of the fstab files but I don't really know. I will try to improve this tree with the device I have but I doubt there is a possibility of a stable rom build from this. And from what i can see, this device's whole repository was meant to be used for a discontinued ROM and this device seems to be abandoned.

**Comment by jmpfbmx** [comment]
@danielkot 

Hi,
It should boot without any prob with my sources.
The only problem will be that RIL and GPS won't work
GPS is prolly bcuz of RIL (Trying to fix it)
Thanks
Regards
Jose
